### ISSUE TITLE
Ometics -> Hirose Adapter

### ISSUE THREAD

**Issue by skeltoh** [MarcelMB/TetrODrive#1]
This looks like a really nice design, and I'm interested in building it and using it with an omnetics based headstage. The manuscript mentioned an monetics->hirose adapter among the design files, but I can't find it.

**Comment by MarcelMB** [comment]
Indeed it is not uploaded. We have used this adapter for multiple purposes and setups in the past that it wasn't part of our "this needs to be uploaded" list.
I will search for the PCB design file and let you know.

**Comment by MarcelMB** [comment]
added them to the files:
[PCB files for Hirose Omnetics Adapter](https://github.com/MarcelMB/TetrODrive/tree/main/PCB_adapter)

Thank you for your feedback!
